version: 2
 
models:
  - name: stg_regions
    columns:
      - name: name
        data_tests:
          - accepted_values:
              values: ['AFRICA','AMERICA','ASIA','EUROPE']
              config:
                store_failures: true
  - name: stg_nations
    columns:
      - name: nation_id
        data_tests:
          - unique
          - not_null
      - name: region_id
        data_tests:
          - relationships:
              to: ref('stg_regions')
              field: region_id
              config:
                store_failures: true