version : 2

sources:
  - name: src
    database: sourcedb
    schema : mk_mall
    tables:
        - name: regions
        - name: nations
        - name: orders
        - name: customers
          config:
           freshness:
             warn_after: {count: 1, period: day}
          loaded_at_field: o_orderdate::timestamp

 